puts "🌱 Seeding recipes ..."

i1 = Ingredient.create(name: "Garlic")
i2 = Ingredient.create(name: "Red Onion")
i3 = Ingredient.create(name: "Pepper")
i4 = Ingredient.create(name: "Salt")
i5 = Ingredient.create(name: "Tomato")
i6 = Ingredient.create(name: "White Onion")
i7 = Ingredient.create(name: "Cumin")
i8 = Ingredient.create(name: "Basil")
i9 = Ingredient.create(name: "Parsley")
i10 = Ingredient.create(name: "Chicken Breast")
i11 = Ingredient.create(name: "Cilantro")
i12 = Ingredient.create(name: "Spaghetti")
i13 = Ingredient.create(name: "Red Pepper Flakes")
i14 = Ingredient.create(name: "Sage")
i15 = Ingredient.create(name: "Bay Leaves")
i16 = Ingredient.create(name: "Tumeric")
i17 = Ingredient.create(name: "Mozzarella")
i18 = Ingredient.create(name: "Parmesan")
i19 = Ingredient.create(name: "Tortillas")
i20 = Ingredient.create(name: "Avocado")
i21 = Ingredient.create(name: "Mushrooms")
i22 = Ingredient.create(name: "Kale")



u1 = User.create(first_name: "Courtney", last_name: "Cash", email: "courtney@gmail.com", password:"password")
u1 = User.create(first_name: "Caitlin", last_name: "Cash", email: "caitlin@gmail.com", password:"password")

r1 = Recipe.create(name:"Spaghetti and Meatballs", cuisine: "Italian", meal: "Dinner", rating:"4/5", description:"long pasta with red sauce and meatballs", image: "https://hips.hearstapps.com/delish/assets/17/39/1506456062-delish-spaghetti-meatballs.jpg", user_id:1)
r2 = Recipe.create(name:"Pancakes", cuisine:"American", meal: "Breakfast", rating:"3/5", description:"Fluffy", image:"https://media.eggs.ca/assets/RecipePhotos/_resampled/FillWyIxMjgwIiwiNzIwIl0/Fluffy-Pancakes-New-CMS.jpg", user_id:1)
r3 = Recipe.create(name:"Shrimp Tacos", cuisine:"Mexican", meal: "Dinner", rating:"5/5", description:"Grilled shrimp, homemade coleslaw wrapped in corn tortillas", image:"https://easyweeknightrecipes.com/wp-content/uploads/2021/02/shrimp-tacos-2.png", user_id:2)
r4 = Recipe.create(name:"BLT", cuisine:"American", meal: "Lunch", rating:"3/5", description:"Bacon, Lettuce, Tomato between two slices of bread ", image:"https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F24%2F2019%2F11%2F13%2FBLT20-20Joy20of20Cooking20-20Heidi_s20Bridge-2000.jpg&q=85", user_id:2)
r5 = Recipe.create(name:"Chocolate Chip Cookies", cuisine:"American", meal: "Dessert", rating:"3/5", description:"Warm,chewy, will melt in your mouth", image:" https://handletheheat.com/wp-content/uploads/2020/10/BAKERY-STYLE-CHOCOLATE-CHIP-COOKIES-9-637x637-1-550x550.jpg", user_id:2)
r6 = Recipe.create(name:"Eggplant Parmesan", cuisine:"Italian", meal: "Dinner", rating:"4/5", description:"Fried Eggplant, smothered in tomato sauce and mozzarella cheese", image:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/2/16/0/FNK_Eggplant-Parmesan-H-111_s4x3.jpg.rend.hgtvcom.616.462.suffix/1518807329709.jpeg", user_id:1)
r7 = Recipe.create(name:"Black Bean Burger", cuisine:"American", meal:"Dinner", rating:"4/5", description:"Patty made of black beans between two buns", image:"https://www.inspiredtaste.net/wp-content/uploads/2020/02/The-Best-Black-Bean-Burger-Recipe-1-1200-1200x800.jpg", user_id:1)
r8 = Recipe.create(name:"Garlic Hummus", cuisine:"Mediterranean", meal:"Snack", rating:"3/5", description:"Blended chickpeas with a garlic touch ", image:"https://cookingwithayeh.com/wp-content/uploads/2020/10/Best-Hummus.jpg", user_id:1)
r9 = Recipe.create(name:"Sausage and Peppers", cuisine:"Italian", meal:"Dinner", rating:"5/5", description:"Pork Sausage and bell peppers, packed with a ton of taste", image:"https://therecipecritic.com/wp-content/uploads/2021/01/skilletsausageandpeppers.jpg", user_id:2)
r10 = Recipe.create(name:"Eggs Benedict", cuisine:"American", meal:"Breakfast", rating:"4/5", description:"Poached eggs with a delicious hollidaise sauce", image:"https://tastesbetterfromscratch.com/wp-content/uploads/2013/08/Eggs-Benedict-11.jpg", user_id:2)
r11 = Recipe.create(name:"Chicken and Waffles", cuisine:"American", meal:"Breakfast", rating:"3/5", description:"Crispy fried chicken on a fluffy Beligum waffle", image:"https://www.lovelesscafe.com/wp-content/uploads/2019/11/chicken-n-waffles-recipe.jpg", user_id:2)
r12 = Recipe.create(name:"Penne alla Vodka", cuisine:"Italian", meal:"Dinner", rating:"5/5", description:"Penne pasta covered with vodka sauce", image:"https://d14iv1hjmfkv57.cloudfront.net/assets/recipes/penne-alla-vodka/_600x600_crop_center-center_61_line/Page-159.jpg?mtime=20200413111343&focal=none&tmtime=20210324094724", user_id:1)
r13 = Recipe.create(name:"Tuna Melt", cuisine:"American", meal:"Lunch", rating:"3/5", description:"Fresh tuna with melted cheese inbetween two slices of bread", image:"https://hips.hearstapps.com/hmg-prod/images/tuna-melt-095-1550261055.jpg", user_id:2)
r14 = Recipe.create(name:"Pad Thai", cuisine:"Thai", meal:"Dinner", rating:"5/5", description:"Rice Noodles with a hearty peanut sauce", image:"https://www.gimmesomeoven.com/wp-content/uploads/2019/01/Pad-Thai-Recipe-1.jpg", user_id:1)
r15 = Recipe.create(name:"Macaroni and Cheese", cuisine:"American", meal:"Dinner", rating:"4/5", description:"Cheesy,creamy, macaroni", image:"https://cdn.loveandlemons.com/wp-content/uploads/2013/01/vegan-mac-and-cheese.jpg", user_id:2)
r16 = Recipe.create(name:"Butternut Squash Soup", cuisine:"American", meal:"Dinner", rating:"5/5", description:"Creamy blended up butternut squash", image:"https://images.themodernproper.com/billowy-turkey/production/posts/2018/roasted-butternut-squash-soup-with-apples-17.jpg?w=1200&auto=compress,format&fit=crop&fp-x=0.5&fp-y=0.5&dm=1599767722&s=1f485307cd9fda8ba10fd2aba6c34559", user_id:1)
r17 = Recipe.create(name:"Lemon-Garlic Kale Salad", cuisine:"American", meal:"Lunch", rating:"4/5", description:"Crunchy fresh Kale with a lemon-garlic dressing", image:"https://static01.nyt.com/images/2020/10/28/dining/garlic-kale-salad/merlin_105432130_4e30fd58-8264-4bdf-95f9-d05db12d0570-articleLarge.jpg", user_id:2)
r18 = Recipe.create(name:"Avocado Toast", cuisine:"American", meal:"Breakfast", rating:"3/5", description:"Avocado on toast", image:"https://cookieandkate.com/images/2012/04/avocado-toast-variations.jpg", user_id:2)
r19 = Recipe.create(name:"Apple Pie", cuisine:"American", meal:"Dessert", rating:"5/5", description:"Warm and sweet", image:"https://i.ytimg.com/vi/RoHWiA6pogg/maxresdefault.jpg", user_id:2)
r20 = Recipe.create(name:"Seven Layer Bars", cuisine:"American", meal:"Dessert", rating:"4/5", description:"7 different layers of sweetness", image:"https://www.iheartnaptime.net/wp-content/uploads/2018/12/7-layer-bars.jpg", user_id:1)
r21 = Recipe.create(name:"Brownies", cuisine:"American", meal:"Breakfast", rating:"3/5", description:"Oooey,Gooey,Fudgey", image:"https://cafedelites.com/wp-content/uploads/2018/02/Best-Fudgiest-Brownies-IMAGE-1001.jpg", user_id:2)
r22 = Recipe.create(name:"Egg Rolls", cuisine:"Chinese", meal:"Side", rating:"5/5", description:"Veggie eggrolls wrapped in crispy eggroll sheets", image:"https://www.jessicagavin.com/wp-content/uploads/2018/01/egg-rolls-10-1200.jpg", user_id:1)
r23 = Recipe.create(name:"Guacmole", cuisine:"Mexican", meal:"Snack", rating:"3/5", description:"Mashed up avocado with tomotoes, red onion, and spices ", image:"https://www.cookingclassy.com/wp-content/uploads/2018/01/guacamole-12.jpg", user_id:2)
r24 = Recipe.create(name:"Pico de Gallo", cuisine:"Mexican", meal:"Snack", rating:"4/5", description:"Tomatoes, red onion, cilantro and lim juice", image:"https://cookieandkate.com/images/2018/09/best-pico-de-gallo-recipe-2.jpg", user_id:1)
r25 = Recipe.create(name:"Pho", cuisine:"Vietnamese", meal:"Dinner", rating:"5/5", description:"Bone broth, noodles, spices and thinly sliced meat", image:"https://www.simplyrecipes.com/thmb/NOwXpq1nenarGiJnOTV7o5Oe_Aw=/1777x1333/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__04__Beef-Pho-LEAD-2-afc6b6a9144947fb9d72070d7ea8c95c.jpg", user_id:2)
r26 = Recipe.create(name:"Fish and Chips", cuisine:"English", meal:"Lunch", rating:"4/5", description:"Fried cod with steak cut fries", image:"https://patch.com/img/cdn20/users/23306266/20210114/024850/styles/patch_image/public/fishandchips___14144820383.jpg", user_id:2)
r27 = Recipe.create(name:"Buffalo Wings", cuisine:"American", meal:"Appetizer", rating:"5/5", description:"Chicken wings smothered in spicy buffalo sauce", image:"https://www.cookingclassy.com/wp-content/uploads/2020/01/buffalo-wings-1.jpg", user_id:2)
r28 = Recipe.create(name:"General Tso Chicken", cuisine:"Chinese", meal:"Dinner", rating:"5/5", description:"Battered chicken smothered in General Tso sauce", image:"https://www.dinneratthezoo.com/wp-content/uploads/2019/07/general-tsos-chicken-4.jpg", user_id:1)
r29 = Recipe.create(name:"Stir Fry Vegetables", cuisine:"American", meal:"Dinner", rating:"3/5", description:"Mixed vegetables in a sweet sauce", image:"https://www.dinneratthezoo.com/wp-content/uploads/2019/02/vegetable-stir-fry-3.jpg", user_id:1)
r30 = Recipe.create(name:"Chili", cuisine:"American", meal:"Dinner", rating:"3/5", description:"Ground beef and beans in a chili sauce", image:"https://theforkedspoon.com/wp-content/uploads/2020/01/The-Best-Chili-Recipe-7.jpg", user_id:2)
r31 = Recipe.create(name:"Crab Rangoon", cuisine:"Asian", meal:"Appetizer", rating:"5/5", description:"Cream cheese and imitation crab, fried in a crunchy dumpling wrapper", image:"https://foodtasia.com/wp-content/uploads/2021/01/crab-rangoon-10.jpg", user_id:1)
r32 = Recipe.create(name:"Salmon Roll", cuisine:"Japanese", meal:"Lunch", rating:"4/5", description:"Salmon, cucumber, avocado, wrapped in seaweed and sushi rice", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP32i63HzXj7Uw5c7MGWNmU24LztkroVAFKQ&usqp=CAU", user_id:1)
r33 = Recipe.create(name:"Cinnamon Rolls", cuisine:"American", meal:"Breakfast", rating:"5/5", description:"Cinnamon wrapped tightly in fluffy dough and baked to perfection", image:"https://www.ambitiouskitchen.com/wp-content/uploads/2017/05/Monique-Cinnamon-Rolls-1.jpg", user_id:1)
r34 = Recipe.create(name:"Blueberry Muffins", cuisine:"American", meal:"Breakfast", rating:"4/5", description:"Muffins baked with fresh blueberries", image:"https://www.inspiredtaste.net/wp-content/uploads/2016/10/Easy-Blueberry-Muffin-Recipe-1-1200.jpg", user_id:2)
r35 = Recipe.create(name:"Quiche", cuisine:"American", meal:"Breakfast", rating:"3/5", description:"Eggs baked on a flakey crust", image:"https://www.wellplated.com/wp-content/uploads/2014/04/Sunburst-Spring-Vegetable-Quiche-with-Puff-Pastry-Crust-Recipe-2.jpg", user_id:1)
r36 = Recipe.create(name:"Pulled Pork Sandwich", cuisine:"American", meal:"Lunch", rating:"3/5", description:"Slow cooked porked, pulled, drenched in BBQ sauce", image:"https://www.thespruceeats.com/thmb/ik1u-0BGFGFae21-gWHcXcE519U=/2696x2696/smart/filters:no_upscale()/slow-cooker-barbecued-boston-butt-3055502-hero-01-c66c1cc5292a476fa7b1c5c760082fc2.jpg", user_id:1)
r37 = Recipe.create(name:"Roasted Broccoli", cuisine:"American", meal:"Side", rating:"4/5", description:"Crunchy broccoli roasted in the oven", image:"https://joyfoodsunshine.com/wp-content/uploads/2019/12/oven-roasted-broccoli-recipe-8.jpg", user_id:2)
r38 = Recipe.create(name:"Asian Green Beans", cuisine:"Asian", meal:"Side", rating:"5/5", description:"Crunchy green beans with a tangy sauce", image:"https://letsdishrecipes.com/wp-content/uploads/2018/10/Asian-Beans-feature-480x360.jpg", user_id:1)
r39 = Recipe.create(name:"Mashed Potatos", cuisine:"American", meal:"Side", rating:"5/5", description:"Yukon gold potatoes boiled and mashed to perfection", image:"https://www.jocooks.com/wp-content/uploads/2019/03/mashed-potatoes-1-7.jpg", user_id:2)
r40 = Recipe.create(name:"Sweet Potato Fries", cuisine:"American", meal:"Side", rating:"3/5", description:"Sweet Potatoes cut thin and fried", image:"https://www.dinneratthezoo.com/wp-content/uploads/2019/07/sweet-potato-fries-5.jpg", user_id:1)
r41 = Recipe.create(name:"Enchildadas", cuisine:"Mexican", meal:"Dinner", rating:"4/5", description:"Cheesy, gooey, saucey", image:"https://www.gimmesomeoven.com/wp-content/uploads/2014/10/The-Best-Chicken-Enchiladas-Recipe-1-1.jpg", user_id:2)
r42 = Recipe.create(name:"Chicken Cutlets", cuisine:"Italian", meal:"Dinner", rating:"3/5", description:"Chicken Breasts pan fried", image:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-190619-parmesan-chicken-cutlets-089-landscape-pf-1561750863.jpg", user_id:1)
r43 = Recipe.create(name:"Cheesecake", cuisine:"American", meal:"Dessert", rating:"5/5", description:"Delightful, creamy, delicious", image:"https://sugarspunrun.com/wp-content/uploads/2019/01/Best-Cheesecake-Recipe-2-1-of-1-4.jpg", user_id:2)
r44 = Recipe.create(name:"Corn Bread", cuisine:"American", meal:"Side", rating:"3/5", description:"Bread made with corn meal", image:"https://www.rockrecipes.com/wp-content/uploads/2015/01/Photo-of-the-best-easy-cornbread-recipe-photo-of-e-servings-stacked-on-a-white-plate.jpg", user_id:1)
r45 = Recipe.create(name:"Lentil Soup", cuisine:"American", meal:"Dinner", rating:"4/5", description:"Brown lentils, boiled into a delicious soup", image:"https://cookieandkate.com/images/2019/01/best-lentil-soup-recipe-4.jpg", user_id:2)
r46 = Recipe.create(name:"Mushroom Risotto", cuisine:"American", meal:"Dinner", rating:"5/5", description:"Creamy rice with sauteed mushrooms", image:"https://www.recipetineats.com/wp-content/uploads/2019/10/Mushroom-Risotto_7.jpg", user_id:1)
# r47 = Recipe.create(name:"", cuisine:"", meal:"", rating:"", description:"", image:"", user_id:2)
# r48 = Recipe.create(name:"", cuisine:"", meal:"", rating:"", description:"", image:"", user_id:1)
# r49 = Recipe.create(name:"", cuisine:"", meal:"", rating:"", description:"", image:"", user_id:2)
# r50 = Recipe.create(name:"", cuisine:"", meal:"", rating:"", description:"", image:"", user_id:1)
# r51 = Recipe.create(name:"", cuisine:"", meal:"", rating:"", description:"", image:"", user_id:2)


ri1 = RecipeIngredient.create(recipe_id: 1, ingredient_id: 1)
ri2 = RecipeIngredient.create(recipe_id: 1, ingredient_id: 2)

puts "✅ Done seeding!"